### ISSUE TITLE
CMS First Post Release Checklist

### ISSUE THREAD

**Issue by carljbowman** [mnylc/libraryfield#1]
# Overview

- [ ] Add Journal link to Nav
- [ ] Update Footer: 
  - [x] Change "Reach Out" to Contact 
  - [ ] Add Newsletter signup
- [ ] Update Get Involved Section on Homepage
  - [x] Remove Jobs link 
  - [x] Change "Reach Out" to Contact 
  - [ ] Add Newsletter signup
- [x] Styles for Contained Image

## Add Journal link to Nav
- [x] Remove commenting on link in `Nav.js` 
<img width="1039" alt="Screenshot 2024-04-25 at 8 43 38 AM" src="https://github.com/mnylc/libraryfield/assets/3409578/60cb70f0-a910-49f1-88c8-18f826848199">

## Add Newsletter to Footer
- [x] Remove commenting on link in `Footer.js` 
- [x] Add link to Newsletter Signup
<img width="1286" alt="Screenshot 2024-04-25 at 8 47 21 AM" src="https://github.com/mnylc/libraryfield/assets/3409578/4c011ee7-14b3-4e69-bbdc-8e7c1e600954">

## Add Newsletter to Get Involved
- [x] Remove commenting on link in `Index.html` 
- [x] Add link to Newsletter Signup
<img width="1293" alt="Screenshot 2024-04-25 at 8 49 08 AM" src="https://github.com/mnylc/libraryfield/assets/3409578/b79eb35e-3ade-4d42-9e40-7c3d1f779a6b">

## Styles for Contained Image
The contained image has a few customizable features:
1. Image Size - _Classes applied directly to the_ `img`
  - `sm` (small)
  - `med` (medium)
3. Background color - _Classes applied to the parent_ `contained-img`
  - None (no class)
  - `sunflower-bg`
  - `newt-bg`
  - `brush-bg`
  - `pine-bg`

![2024-04-25 08 52 35](https://github.com/mnylc/libraryfield/assets/3409578/f9d18a0c-91b9-4e08-acf8-8823a2ce55ba)
